---
- name: Get FortiGate system status via SSH CLI
  hosts: all
  gather_facts: no

  vars:
    ansible_connection: ssh
    ansible_shell_type: sh

  tasks:
    - name: Get system status (CLI)
      ansible.builtin.raw: |
        get system status
      register: system_status

    - name: Show system status output
      debug:
        var: system_status.stdout_lines
