---
- name: Get Fortigate user group information
  hosts: fortigate1
  connection: httpapi
  gather_facts: false   # <-- Add this line
  collections:
  - fortinet.fortios

  tasks:

  - name: Get user group info
    fortios_configuration_fact:
      vdom: ""
      selector: user_group

    register: user_group
  - name: Show user group info
    debug:
      var: user_group

