---
- name: add or remove route filters to a router config.
  hosts: junosdevices2
  gather_facts: no

  #Usage:
  #ansible-playbook junos_add_route_filter.yml -u admin -k -vvv --extra-vars '{"group":"vpn667","action":"delete","device_list":["10.0.50.0/24","10.0.51.0/24","10.0.52.0/24","10.0.53.0/24"]}'

  tasks:

    - name: add or remove route filters to a router config.
      junipernetworks.junos.junos_config:
        lines:
        - " {{action}} groups {{ group }} policy-options policy-statement {{ group }} from route-filter {{ item }} orlonger "
      loop: "{{ device_list }}"
      loop_control:
         loop_var: item
