---
- name: Set hostname on Arista EOS device
  hosts: arista
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: arista.eos.eos

  tasks:
    - name: Configure hostname
      arista.eos.eos_config:
        lines:
          - hostname aristasw1
        save_when: modified
