- name: Configure Syslog Server on Juniper Switches
  hosts: all
  gather_facts: no

  tasks:
    - name: Generate syslog configuration from template
      template:
        src: syslog.j2
        dest: "/tmp/syslog_{{ inventory_hostname }}.conf"

    - name: Apply syslog configuration to switch
      juniper.device.config:
        src: "/tmp/syslog_{{ inventory_hostname }}.conf"
        format: text
        load: merge
        commit: true

