---
- name: Configure NTP and DNS on Juniper Devices
  hosts: all
  gather_facts: no
  connection: juniper.device.pyez



  tasks:
    - name: Generate configuration from Jinja2 template
      template:
        src: junos_ntp_dns.j2
        dest: "/tmp/dns_ntp_{{ inventory_hostname }}.conf"

    - name: Apply NTP and DNS configuration to switch
      juniper.device.config:
        src: "/tmp/dns_ntp_{{ inventory_hostname }}.conf"
        format: text
        load: merge
        commit: true
