---
- name: "Get Junos OS configuration"
  hosts: dc1
  gather_facts: no

  tasks:
    #- name: backup
    #  junos_config:
    #    src: '/config/juniper.conf.gz'
    #    backup: true
    #    comment: update config

    - name: Backup current switch config (junos)
      junipernetworks.junos.junos_config:
        backup: yes
      register: backup_junos_location
      when: ansible_network_os == 'junipernetworks.junos.junos'
