- name: Add superuser to Juniper Switches
  hosts: all
  gather_facts: no

  tasks:
    - name: Generate superuser configuration from template
      template:
        src: superuser.j2
        dest: "/tmp/superuser_{{ inventory_hostname }}.conf"

    - name: Apply superuser configuration to switch
      juniper.device.config:
        src: "/tmp/superuser_{{ inventory_hostname }}.conf"
        format: text
        load: merge
        commit: true

