---
- name: show version and other user level commands
  hosts: all
  gather_facts: no
  connection: netconf
  
  tasks:
   - name: run show version and show interfaces on remote devices
     junipernetworks.junos.junos_command:
       commands: show version, show interfaces

     register: print_output

   - name: Print version
     debug:
        var=print_output.stdout_lines
