- name: Change Juniper EX Switch Hostname
  hosts: all
  gather_facts: no
  connection: juniper.device.pyez

  tasks:
    - name: Generate hostname configuration from template
      template:
        src: hostname2.j2
        dest: "/tmp/hostname_{{ inventory_hostname }}.conf"

    - name: Apply hostname configuration to switch
      juniper.device.config:
        src: "/tmp/hostname_{{ inventory_hostname }}.conf"
        format: text
        load: merge
        commit: true

