---
- name: Configure Time Zone on Juniper Devices
  hosts: all
  gather_facts: no
  connection: juniper.device.pyez

    #vars:
    # timezone: "America/New_York"

  tasks:
    - name: Generate timezone configuration from Jinja2 template
      template:
        src: junos_timezone.j2
        dest: "/tmp/timezone_{{ inventory_hostname }}.conf"

    - name: Apply timezone configuration to Juniper device
      juniper.device.config:
        src: "/tmp/timezone_{{ inventory_hostname }}.conf"
        format: text
        load: merge
        commit: true

