---
- name: Add VRF to a CSR1000v router.
  hosts: csr1000vlab01
  connection: network_cli
  gather_facts: no

  tasks:
    - name: configure a vrf named act202
      ios_vrf:
        name: act202
        description: act202
        interfaces:
          - GigabitEthernet2.202
