---
- name: Configure NTP (VRF mgmt)
  hosts: all
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Configure NTP + ACL + VRF server
      cisco.ios.ios_config:
        lines:
          - access-list 22 permit any log
          - ntp source GigabitEthernet1
          - ntp logging
          - ntp access-group peer 22
          - ntp server vrf mgmt 10.0.30.1
