---
- name: Add IP and shut interface
  hosts: csr
  connection: network_cli
  gather_facts: no

  tasks:
    - name: configure interface settings
      ios_config:
        lines:
          - description test_interface
          - ip address 172.31.1.1 255.255.255.0
          - no shutdown
        interface: interface GigabitEthernet4

