---
- name: Syslog Configuration
  hosts: all
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Configure syslog settings (global)
      cisco.ios.ios_logging_global:
        config:
          hosts:
            - hostname: 10.0.0.236
              transport:
                udp:
                  port: 514
          trap: informational
        state: merged
