---

- name: Delete a VIP, pool and pool members
  hosts: all
  connection: local

  vars:
    provider:
      password: "password"
      server: 10.0.40.51
      user: "user":
      validate_certs: no
      server_port: 443

  tasks:
  - name: Delete a VIP
    bigip_virtual_server:
      provider: "{{ provider }}"
      description: foo-vip
      destination: 172.16.10.108
      name: vip-1
      pool: web
      port: "80"
      snat: Automap
      state: absent
      profiles:
        - http
        - clientssl
    delegate_to: localhost

  - name: Remove members from pool
    bigip_pool_member:
      provider: "{{ provider }}"
      description: "webserver {{ item.name }}"
      host: "{{ item.host }}"
      name: "{{ item.name }}"
      pool: web
      port: 80
      state: absent
    with_items:
      - host: 10.10.10.10
        name: web01
        description: web01
      - host: 10.10.10.20
        name: web02
        description: web02
    delegate_to: localhost

  - name: Delete a pool
    bigip_pool:
        provider: "{{ provider }}"
        lb_method: ratio-member
        name: web
        slow_ramp_time: 120
        state: absent
    delegate_to: localhost

#  - name: Add members to pool
#    bigip_pool_member:
#      provider: "{{ provider }}"
#      description: "webserver {{ item.name }}"
#      host: "{{ item.host }}"
#      name: "{{ item.name }}"
#      pool: web
#      port: 80
#      state: absent
#    with_items:
#      - host: 10.10.10.10
#        name: web01
#        description: web01
#      - host: 10.10.10.20
#        name: web02
#        description: web02
#    delegate_to: localhost



#  - name: Create a VIP
#    bigip_virtual_server:
#      provider: "{{ provider }}"
#      description: foo-vip
#      destination: 172.16.10.108
#      name: vip-1
#      pool: web
#      port: 80
#      snat: Automap
#      state: absent
#      profiles:
#        - http
#        - clientssl
#    delegate_to: localhost

# source : https://clouddocs.f5.com/products/orchestration/ansible/devel/
  

