---
- name: Get free memory from linux servers
  hosts: all
  tasks:
  - name: Execute 'free -m'  using the shell module
    shell: 'free -m'
    register: results

  - name: Display results of 'free -m'
    debug:
      var: results


# Validated: 2/26/2026
